name: Checkov

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  checkov:
    permissions:
      contents: read
      security-events: write
      actions: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0 # pragma: allowlist secret

      - name: Checkov GitHub Action
        uses: bridgecrewio/checkov-action@eec884fd62682f5f2b33e303e160d5e2fe8d89ec # v12.3052.0 # pragma: allowlist secret
        with:
          directory: .
          soft_fail: true
          output_format: cli
          output_file_path: console
