name: pre-merge check

on:
  workflow_call:
    inputs:
      gitRef:
        required: false
        type: string
        default: ${{ github.ref }}
  workflow_dispatch:
  pull_request:
      types: [opened, synchronize, reopened]
  push:
    branches:
      - main

permissions: read-all

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    timeout-minutes: 7
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout repo
        uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # pin@v3
        with:
          fetch-depth: 0

      - name: Set up AWS creds
        uses: aws-actions/configure-aws-credentials@e1e17a757e536f70e52b5a12b2e8d1d1c60e04ef # pin@v1-node16
        with:
          role-to-assume: ${{ secrets.CloudFormationStackTestingGitHubActionsRole }}
          aws-region: eu-west-2

  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    timeout-minutes: 60
    permissions:
      id-token: write
      contents: read
    needs: deploy
    steps:
      - name: Checkout repo
        uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # pin@v3
        with:
          fetch-depth: 0

      - uses: govuk-one-login/github-actions/sam/check-stack-updated@a95754d9c2eca71d3334d5c023b2dd379818c60c #bau-new-cloudformation-polling-action
        with:
          stack-name: home-backend
          gh-polling-role: ${{ secrets.CloudFormationStackPollingGitHubActionsRole }}


