name: CloudFormation Linter

on:
  pull_request:
    paths-ignore:
      - "deploy.yaml"

jobs:
  lint_cloudformation:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "No changes to Cloudformation files - skipping checks"'
